"""add_portfolio_summary_columns

Revision ID: 0838f567cf6c
Revises: f75f0dda9444
Create Date: 2026-01-16 15:16:05.045437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0838f567cf6c'
down_revision: Union[str, None] = 'f75f0dda9444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('source_portfolio_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('portfolios', sa.Column('scenario_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('portfolios', sa.Column('scenario_description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))
    op.create_index(op.f('ix_portfolios_source_portfolio_id'), 'portfolios', ['source_portfolio_id'], unique=False)
    op.create_foreign_key(None, 'portfolios', 'portfolios', ['source_portfolio_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'portfolios', type_='foreignkey')
    op.drop_index(op.f('ix_portfolios_source_portfolio_id'), table_name='portfolios')
    op.drop_column('portfolios', 'scenario_description')
    op.drop_column('portfolios', 'scenario_name')
    op.drop_column('portfolios', 'source_portfolio_id')
    # ### end Alembic commands ###
